// Generates src/accents.css. The app's accent is Tailwind's `violet-*` (plus `indigo-700` in the hero
// gradient), so a colour theme just points those variables at another palette: every utility, in light and
// dark, follows with no component changes. Run: node scripts/gen-accents.mjs
//
// `shift` moves the darker shades one step (600 -> 700, ...) for hues whose 600 is too pale for white text
// (green, slate), keeping buttons readable.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

export const ACCENTS = [
  { id: 'ocean', primary: 'blue', second: 'cyan', shift: 0 },
  { id: 'forest', primary: 'green', second: 'teal', shift: 1 },
  { id: 'sunset', primary: 'pink', second: 'orange', shift: 0 },
  { id: 'graphite', primary: 'slate', second: 'zinc', shift: 1 }
];

const shades = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
const shifted = { 400: 500, 500: 600, 600: 700, 700: 800, 800: 900, 900: 950 };
const pick = (n, shift) => (shift && shifted[n] ? shifted[n] : n);

let css = `/* GENERATED by scripts/gen-accents.mjs. Do not edit by hand.
   Colour themes: re-point the accent (violet, plus indigo-700) at another palette. Violet is the default. */\n`;
for (const a of ACCENTS) {
  css += `\nhtml[data-accent='${a.id}'] {\n`;
  for (const n of shades) css += `  --color-violet-${n}: var(--color-${a.primary}-${pick(n, a.shift)});\n`;
  css += `  --color-indigo-700: var(--color-${a.second}-700);\n}\n`;
}
writeFileSync(join(import.meta.dirname, '..', 'src', 'accents.css'), css);
console.log(`wrote src/accents.css for ${ACCENTS.map((a) => a.id).join(', ')}`);
