// Writes src/accents.css: one block per Colour Theme that re-points `--color-primary-*` at another
// Tailwind palette. Forest is the `@theme` default in src/app.css, so it needs no block here.
// Run `node scripts/gen-accents.mjs` after changing the palettes below, then check in the output.
// The palettes are shifted one step darker, as Forest's is, so white on primary-600 stays readable.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

/** Colour Theme -> the Tailwind palette it uses. Keep in step with src/lib/core/colour-theme.ts. */
const palettes = { violet: 'violet', ocean: 'sky', sunset: 'orange', graphite: 'slate' };

/** primary step -> the palette step it points at. */
const steps = {
  50: 50,
  100: 100,
  200: 200,
  300: 300,
  400: 500,
  500: 600,
  600: 700,
  700: 800,
  800: 900,
  900: 950,
  950: 950,
};

const block = ([theme, palette]) =>
  `html[data-accent='${theme}'] {\n${Object.entries(steps)
    .map(([step, from]) => `  --color-primary-${step}: var(--color-${palette}-${String(from)});`)
    .join('\n')}\n}\n`;

const css = `/* Generated by scripts/gen-accents.mjs. Do not edit by hand. */\n${Object.entries(
  palettes,
)
  .map(block)
  .join('\n')}`;

writeFileSync(fileURLToPath(new URL('../src/accents.css', import.meta.url)), css);
